# Generated by Django 5.2.7 on 2026-02-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acg_core', '0002_user_avatar_user_birthday_user_gender_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='female', max_length=20),
        ),
    ]
