# Generated by Django 5.0.3 on 2026-02-07 10:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
            },
        ),
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='板块名称')),
                ('description', models.TextField(blank=True, verbose_name='板块描述')),
                ('icon', models.CharField(default='fa-comments', max_length=50, verbose_name='图标类名(FontAwesome)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '社区板块',
                'verbose_name_plural': '社区板块',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('summary', models.TextField(blank=True, max_length=500, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news_covers/', verbose_name='封面图')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.newscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '资讯新闻',
                'verbose_name_plural': '资讯新闻',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='置顶')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.topiccategory', verbose_name='板块')),
            ],
            options={
                'verbose_name': '社区话题',
                'verbose_name_plural': '社区话题',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
    ]
