# Generated by Django 5.0.3 on 2026-02-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.CharField(blank=True, help_text='用逗号或空格分隔', max_length=255, verbose_name='关键词'),
        ),
    ]
