# Generated by Django 5.0.3 on 2026-02-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_topic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, help_text='用逗号或空格分隔', max_length=255, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.newscategory', verbose_name='分类'),
        ),
    ]
