# Generated by Django 5.0.3 on 2026-02-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_news_tags_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
