# Generated by Django 5.0.3 on 2026-02-10 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_newscomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscomment',
            options={'ordering': ['created_at'], 'verbose_name': '资讯评论', 'verbose_name_plural': '资讯评论'},
        ),
        migrations.AddField(
            model_name='newscomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.newscomment', verbose_name='父评论'),
        ),
        migrations.CreateModel(
            name='TopicComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.topiccomment', verbose_name='父评论')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.topic', verbose_name='所属话题')),
            ],
            options={
                'verbose_name': '话题评论',
                'verbose_name_plural': '话题评论',
                'ordering': ['created_at'],
            },
        ),
    ]
