# Generated by Django 5.2.7 on 2026-02-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('zone', models.CharField(choices=[('anime', '番剧'), ('galgame', 'Galgame'), ('manga', '小说/漫画')], max_length=20, verbose_name='专区')),
                ('tag', models.CharField(help_text='例如：热血/战斗', max_length=100, verbose_name='标签')),
                ('hot_score', models.FloatField(default=0.0, verbose_name='评分')),
                ('views', models.IntegerField(default=0, verbose_name='点击量/热度')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='works/covers/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
