# Generated by Django 5.2.7 on 2026-02-11 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='标签名称')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('zone', models.CharField(choices=[('anime', '番剧'), ('galgame', 'Galgame'), ('manga', '小说/漫画')], max_length=20, verbose_name='专区')),
                ('description', models.TextField(help_text='简单介绍下这部作品吧...', verbose_name='作品简介')),
                ('release_date', models.DateField(verbose_name='作品官方发布日期')),
                ('hot_score', models.FloatField(default=0.0, verbose_name='评分')),
                ('views', models.IntegerField(default=0, verbose_name='点击量/热度')),
                ('cover', models.ImageField(upload_to='works/covers/', verbose_name='封面图')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='推荐者')),
                ('tags', models.ManyToManyField(blank=True, to='masterpieces.tag', verbose_name='标签')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='masterpieces.work')),
            ],
            options={
                'verbose_name': '作品评论',
                'verbose_name_plural': '作品评论',
            },
        ),
    ]
