# Generated by Django 5.2.7 on 2026-02-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0004_workgallery_uploader'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workgallery',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='workgallery',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
