# Generated by Django 5.2.7 on 2026-02-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0005_alter_workgallery_options_workgallery_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='hide_day',
            field=models.BooleanField(default=False, verbose_name='隐藏日期'),
        ),
        migrations.AddField(
            model_name='work',
            name='hide_month',
            field=models.BooleanField(default=False, verbose_name='隐藏月份'),
        ),
    ]
