# Generated by Django 5.2.7 on 2026-02-27 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0006_work_hide_day_work_hide_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_works', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
