# Generated by Django 5.2.7 on 2026-03-07 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0007_work_favorites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Illustration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('work_type', models.CharField(choices=[('original', '原创'), ('repost', '搬运')], max_length=20, verbose_name='作品性质')),
                ('description', models.TextField(verbose_name='作品介绍')),
                ('author_bio', models.CharField(max_length=200, verbose_name='画师简介')),
                ('image', models.ImageField(upload_to='illustrations/%Y/%m/', verbose_name='插画文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='masterpieces.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
