# Generated by Django 5.2.7 on 2026-03-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0008_illustration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illustration',
            options={},
        ),
        migrations.RemoveField(
            model_name='illustration',
            name='author_bio',
        ),
        migrations.AlterField(
            model_name='illustration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='description',
            field=models.TextField(verbose_name='作品描述'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='tags',
            field=models.ManyToManyField(blank=True, to='masterpieces.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='illustration',
            name='work_type',
            field=models.CharField(choices=[('original', '原创'), ('repost', '搬运')], default='repost', max_length=20, verbose_name='作品性质'),
        ),
    ]
