# Generated by Django 5.2.7 on 2026-03-08 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0010_illustrationcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_illustrations', to=settings.AUTH_USER_MODEL, verbose_name='收藏者'),
        ),
    ]
