# Generated by Django 5.2.7 on 2026-03-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpieces', '0011_illustration_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='illustration',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
