# Generated by Django 5.0.3 on 2026-02-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='relationship_type',
            field=models.CharField(choices=[('normal', '普通好友'), ('bestie', '基友/死党'), ('lover', '情侣/CP'), ('family', '家人')], default='normal', max_length=20, verbose_name='关系类型'),
        ),
    ]
