# Generated by Django 5.2.7 on 2026-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_friendship_relationship_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_real',
            field=models.BooleanField(default=True, verbose_name='邮箱是否真实'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_real',
            field=models.BooleanField(default=True, verbose_name='手机号是否真实'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=11111111111, max_length=11, unique=True, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
