# Generated by Django 5.2.7 on 2026-02-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_email_real_user_is_phone_real_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_email_real',
            field=models.BooleanField(default=False, verbose_name='邮箱是否真实'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_phone_real',
            field=models.BooleanField(default=False, verbose_name='手机号是否真实'),
        ),
    ]
