# Generated by Django 5.2.7 on 2026-02-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_is_email_real_alter_user_is_phone_real'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='偏好设置'),
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_tags',
            field=models.JSONField(blank=True, default=dict, verbose_name='插画标签浏览统计'),
        ),
    ]
