# Generated by Django 5.2.7 on 2026-03-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_preferences_user_viewed_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(default='male', max_length=20, verbose_name='性别'),
        ),
    ]
